# Generated by Django 5.0.6 on 2024-07-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='username',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
