# Generated by Django 5.0.6 on 2024-07-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmed', '0002_alter_logininfo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='username',
            field=models.CharField(max_length=16),
        ),
    ]
